In [11]:
## Numpy
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [7]:
## linear algebra

X = np.random.random([10, 10])
b = np.random.random([10, 1])

np.linalg.solve(X, b)

array([[-10.28440365],
       [ -6.17316455],
       [ 12.21326946],
       [ -1.07572733],
       [  2.45379397],
       [ 10.15215779],
       [ -0.66647475],
       [  2.55850181],
       [ -7.90290827],
       [ -5.18786435]])

In [9]:
np.linalg.lstsq(X, b)

C:\ProgramData\Miniconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([[-10.28440365],
        [ -6.17316455],
        [ 12.21326946],
        [ -1.07572733],
        [  2.45379397],
        [ 10.15215779],
        [ -0.66647475],
        [  2.55850181],
        [ -7.90290827],
        [ -5.18786435]]),
 array([], dtype=float64),
 10,
 array([5.46459215, 1.71298002, 1.2471811 , 1.03904838, 0.83414146,
        0.62174965, 0.47257332, 0.34385044, 0.29170159, 0.01450516]))

In [17]:
## pandas

import pandas as pd

## There are two data sturcures that must very familiar
from pandas import DataFrame, Series

In [20]:
## series
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [22]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [23]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [24]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [27]:
obj2.values

array([ 4,  7, -5,  3], dtype=int64)

In [28]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [34]:
obj2['a'], obj2['b']

(-5, 7)

In [35]:
obj2[['b', 'c']]

b    7
c    3
dtype: int64

In [36]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [38]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [39]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [40]:
## dict like
'b' in obj2

True

In [41]:
'e' in obj2

False

In [42]:
## construct serie from dict
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [44]:
## override index key
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [49]:
## NaN, null value
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [50]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [54]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [56]:
## both seria and index have name attirbute
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [57]:
## DataFrame

data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [58]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [60]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [63]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [64]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [66]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [69]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [71]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [73]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [75]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [77]:
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [78]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [79]:
del frame2['eastern']
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [ ]:
## reindex
## drop